"""
This file defines all the error codes and error messages used in Telescope.
"""

REASON_BAD_PASSKEY = 10001
REASON_NO_PASSKEY = 10002
REASON_LEECHING_FORBIDDEN = 10003

REASON_UNREGISTERED_TORRENT = 10101

REASON_REQUEST_ERROR = 10201
REASON_REQUEST_NO_INFO_HASH = 10202
REASON_REQUEST_NO_PEER_ID = 10203
REASON_REQUEST_NO_PORT = 10204
REASON_REQUEST_BAD_INFO_HASH = 10205
REASON_REQUEST_BAD_PEER_ID = 10206
REASON_REQUEST_BAD_NUMWANT = 10207

REASONS = {
    REASON_BAD_PASSKEY: 'Invalid passkey',
    REASON_NO_PASSKEY: 'Passkey not provided',
    REASON_LEECHING_FORBIDDEN: 'Leeching forbidden',
    REASON_UNREGISTERED_TORRENT: 'Unregistered torrent',
    REASON_REQUEST_ERROR: 'Error in provided parameters',
    REASON_REQUEST_NO_INFO_HASH: 'No info_hash provided',
    REASON_REQUEST_NO_PEER_ID: 'No peer_id provided',
    REASON_REQUEST_NO_PORT: 'No port provided',
    REASON_REQUEST_BAD_INFO_HASH: 'Bad info_hash provided',
    REASON_REQUEST_BAD_PEER_ID: 'Bad peer_id. You are probably using a banned client. Please check http://pwnnetwork.net/rules.php?p=clients',
    REASON_REQUEST_BAD_NUMWANT: 'numwant must be less than 250',
    }

REASONS_CODE = {
    REASON_UNREGISTERED_TORRENT: 200,
    REASON_REQUEST_NO_INFO_HASH: 101,
    REASON_REQUEST_NO_PEER_ID: 102,
    REASON_REQUEST_NO_PORT: 103,
    REASON_REQUEST_BAD_INFO_HASH: 150,
    REASON_REQUEST_BAD_PEER_ID: 151,
    REASON_REQUEST_BAD_NUMWANT: 152,
    }
